---
- name: Deploying app
  hosts: all
  vars:
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: git@github.com:markelarauzo7/symfony-hex-arch-skeleton.git
    ansistrano_git_branch: master
    ansistrano_deploy_to: "/var/www/app"
    ansistrano_keep_releases: 5
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/before-symlink.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/after-symlink.yml"
    ansistrano_before_cleanup_tasks_file: "{{ playbook_dir }}/custom-tasks/before-cleanup.yml"
    ansistrano_allow_anonymous_stats: no
    php_version: "8.0"
    install_bundle_assets: true
  roles:
    - { role: ansistrano.deploy }