index:
  path: /
  controller: Project\Aggregate\Infrastructure\WebController::indexAction
  methods:
    - GET

indexAPI:
  path: /api
  controller: Project\Aggregate\Infrastructure\APIController::indexAction
  methods:
    - GET