---
- name: Copy env.local file. Assuming it exists
  shell: cp .env.local "{{ ansistrano_release_path.stdout }}/.env.local"
  args:
    chdir: /var/www/app/

- name: Install composer dependencies with performant autoloader
  shell: composer install --no-autoloader --no-scripts --no-interaction --no-dev && composer dump-autoload --optimize --classmap-authoritative
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Execute migrations
  shell: make migrate
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Change var directory permissions to 777 
  file:
    path: "{{ ansistrano_release_path.stdout }}/var"
    state: directory
    mode: '0777'
    follow: true
    recurse: true