---
- name: Deploying api
  hosts: all
  vars:
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: git@github.com:treefy/treefy.git
    ansistrano_git_branch: master
    ansistrano_deploy_to: "/var/www/api"
    ansistrano_keep_releases: 7
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/before-symlink.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/after-symlink.yml"
    ansistrano_before_cleanup_tasks_file: "{{ playbook_dir }}/custom-tasks/before-cleanup.yml"
    install_bundle_assets: true
    ansistrano_allow_anonymous_stats: no
  roles:
    - { role: ansistrano.deploy }