---
- name: Rollback api
  hosts: all
  vars:
    ansistrano_deploy_to: "/var/www/api"
    ansistrano_remove_rolled_back: yes
    ansistrano_rollback_before_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/before-symlink-rollback.yml"
    ansistrano_rollback_after_symlink_tasks_file: "{{ playbook_dir }}/custom-tasks/after-symlink.yml"
  roles:
    - { role: ansistrano.rollback }