doctrine_migrations:
    dir_name: '%kernel.project_dir%/app/doctrine/db/migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
