# https://symfony.com/doc/current/reference/configuration/doctrine.html
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

# php bin/console debug:config doctrine
doctrine:
    dbal:
        default_connection: 'default'
        connections:

            default:
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.1.38'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
                
            # In memory SQLite database for running tests faster. There are differences with MySQL so you might find inconsistencies
            test:
                driver: 'pdo_sqlite'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                memory: true
    orm:
        auto_generate_proxy_classes: true
        #   naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Project:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/app/db/doctrine/mysql/mappings'
                prefix: 'Project'
